# Generated by Django 5.2.6 on 2025-09-05 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='챌린지 제목')),
                ('description', models.TextField(verbose_name='챌린지 설명')),
                ('challenge_type', models.CharField(choices=[('DRINK_COUNT', '추천 차 마시기 횟수'), ('RECORD_COUNT', '기록 작성 횟수'), ('UNIQUE_TEA_COUNT', '서로 다른 종류의 차 마시기'), ('CONSECUTIVE_DAYS', '연속으로 차 마시기')], max_length=50, verbose_name='챌린지 종류')),
            ],
        ),
        migrations.CreateModel(
            name='TeaLogs',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True, verbose_name='차 마신 날짜')),
                ('tea_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teas.tea', verbose_name='차 아이디')),
            ],
        ),
    ]
