# Generated by Django 5.2.6 on 2025-09-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tealogs',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tealogs',
            name='feeling',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
