# Generated by Django 5.2.6 on 2025-09-05 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_tealogs_comment_tealogs_feeling'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tealogs',
            old_name='date',
            new_name='created_at',
        ),
    ]
