# Generated by Django 5.2.6 on 2025-09-05 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_rename_date_tealogs_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tealogs',
            old_name='tea_id',
            new_name='tea',
        ),
    ]
