# Generated by Django 5.2.6 on 2025-09-05 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_rename_tea_id_tealogs_tea'),
        ('teas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentRecommendedTea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('tea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teas.tea')),
            ],
        ),
    ]
