# Generated by Django 5.2.6 on 2025-09-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_recentrecommendedtea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tealogs',
            name='feeling',
            field=models.CharField(blank=True, choices=[('좋았어요', '좋았어요'), ('그냥그래요', '그냥그래요'), ('별로에요', '별로에요')], max_length=10, null=True),
        ),
    ]
