# Generated by Django 5.2.6 on 2025-09-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tea',
            name='taste_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
